/* fluent-emoji.js — Fluent Emoji (Microsoft) via CDN
   Replaces emoji characters with beautiful 3D/flat Fluent Emoji images.
   Usage: fe('🚛') → <img class="fe" src="..." alt="🚛" />
*/

const FE = {
  // Map emoji → Fluent Emoji asset name
  map: {
    '🚛': 'heavy-truck',
    '📦': 'package',
    '✅': 'check-mark-button',
    '⭐': 'star',
    '💰': 'money-bag',
    '🗺️': 'world-map',
    '💳': 'credit-card',
    '🤖': 'robot',
    '🛒': 'shopping-cart',
    '👤': 'bust-in-silhouette',
    '🏠': 'house',
    '📍': 'round-pushpin',
    '🔍': 'magnifying-glass',
    '🎉': 'party-popper',
    '⏳': 'hourglass-done',
    '❌': 'cross-mark',
    '📭': 'open-mailbox',
    '📋': 'clipboard',
    '✏️': 'pencil',
    '❄️': 'snowflake',
    '🚚': 'delivery-truck',
    '🚜': 'tractor',
    '🚐': 'minibus',
    '🏍️': 'motorcycle',
    '🚗': 'automobile',
    '⚙️': 'gear',
    '🔧': 'wrench',
    '📄': 'page-facing-up',
    '🪪': 'identification-card',
    '📏': 'ruler',
    '🌳': 'deciduous-tree',
    '📱': 'mobile-phone',
    '🌍': 'earth-globe-europe-africa',
    '⬇️': 'down-arrow',
    '🌿': 'herb',
    '🥦': 'broccoli',
    '🍎': 'red-apple',
    '🌾': 'sheaf-of-rice',
    '🥛': 'glass-of-milk',
    '🍯': 'honey-pot',
    '🥬': 'leafy-green',
    '🧠': 'brain',
    '📊': 'bar-chart',
    '📈': 'chart-increasing',
    '📉': 'chart-decreasing',
    '💡': 'light-bulb',
    '🔥': 'fire',
    '❤️': 'red-heart',
    '👍': 'thumbs-up',
    '👎': 'thumbs-down',
    '💬': 'speech-balloon',
    '📢': 'loudspeaker',
    '🔔': 'bell',
    '🔕': 'bell-with-slash',
    '📎': 'paperclip',
    '🗑️': 'wastebasket',
    '🔢': 'input-numbers',
    '🟢': 'green-circle',
    '🔴': 'red-circle',
    '🟡': 'yellow-circle',
    '💸': 'money-with-wings',
    '📊': 'bar-chart',
    '🧾': 'receipt',
    '🛒': 'shopping-cart',
    '🌱': 'seedling',
    '❄️': 'snowflake',
    '🌡️': 'thermometer',
    '⚖️': 'balance-scale',
    '📅': 'calendar',
    '🏷️': 'label',
    '📸': 'camera',
    '🎬': 'clapper-board',
    '📝': 'memo',
    '🗂️': 'card-index',
    '💼': 'briefcase',
    '🎓': 'graduation-cap',
    '🔑': 'key',
    '🔐': 'locked-with-key',
    '🔒': 'locked',
    '🔓': 'unlocked',
    '🛡️': 'shield',
    '✅': 'check-mark-button',
    '🚫': 'prohibited',
    '⚠️': 'warning',
    'ℹ️': 'information',
    '❓': 'question-mark',
    '❗': 'exclamation-mark',
    '💯': 'hundred-points',
    '🎯': 'bullseye',
    '🏆': 'trophy',
    '🥇': 'gold-medal',
    '🥈': 'silver-medal',
    '🥉': 'bronze-medal',
    '🎪': 'circus-tent',
    '🎨': 'artist-palette',
    '🎵': 'musical-note',
    '🎶': 'musical-notes',
    '🎸': 'guitar',
    '🎹': 'musical-keyboard',
    '🎺': 'trumpet',
    '🥁': 'drum',
    '🎷': 'saxophone',
    '🎻': 'violin',
    '🎤': 'microphone',
    '🎧': 'headphone',
    '📻': 'radio',
    '📺': 'television',
    '📷': 'camera',
    '📹': 'video-camera',
    '📽️': 'film-projector',
    '🎞️': 'film-frames',
    '🖥️': 'desktop-computer',
    '🖨️': 'printer',
    '⌨️': 'keyboard',
    '🖱️': 'computer-mouse',
    '💾': 'floppy-disk',
    '💿': 'optical-disk',
    '📀': 'dvd',
    '🧮': 'abacus',
    '🗜️': 'compression',
    '🔒': 'locked',
    '🔓': 'unlocked',
    '🔑': 'key',
    '🗝️': 'old-key',
    '🔨': 'hammer',
    '⚒️': 'hammer-and-pick',
    '🛠️': 'hammer-and-wrench',
    '🗡️': 'dagger',
    '⚔️': 'crossed-swords',
    '🔫': 'pistol',
    '🏹': 'bow-and-arrow',
    '🛡️': 'shield',
    '🔧': 'wrench',
    '🔩': 'nut-and-bolt',
    '⚙️': 'gear',
    '🗜️': 'compression',
    '⚖️': 'balance-scale',
    '🔗': 'link',
    '⛓️': 'chains',
    '🪝': 'hook',
    '🧰': 'toolbox',
    '🧲': 'magnet',
    '🧪': 'test-tube',
    '🧫': 'petri-dish',
    '🧬': 'dna',
    '🔬': 'microscope',
    '🔭': 'telescope',
    '📡': 'satellite-antenna',
    '💉': 'syringe',
    '🩸': 'drop-of-blood',
    '💊': 'pill',
    '🩹': 'adhesive-bandage',
    '🩺': 'stethoscope',
    '🚪': 'door',
    '🛗': 'elevator',
    '🪞': 'mirror',
    '🪟': 'window',
    '🛏️': 'bed',
    '🛋️': 'couch-and-lamp',
    '🪑': 'chair',
    '🚽': 'toilet',
    '🪠': 'plunger',
    '🚿': 'shower',
    '🛁': 'bathtub',
    '🪤': 'mouse-trap',
    '🪒': 'razor',
    '🧴': 'lotion-bottle',
    '🧷': 'safety-pin',
    '🧹': 'broom',
    '🧺': 'basket',
    '🧻': 'roll-of-paper',
    '🪣': 'bucket',
    '🧼': 'soap',
    '🫧': 'bubbles',
    '🪥': 'toothbrush',
    '🧽': 'sponge',
    '🧯': 'fire extinguisher',
    '🛒': 'shopping-cart',
    '🚬': 'cigarette',
    '⚰️': 'coffin',
    '🪦': 'headstone',
    '⚱️': 'funeral-urn',
    '🗿': 'moai',
    '🪧': 'placard',
    '🪪': 'identification-card',
    '🏧': 'atm-sign',
    '🚮': 'litter-in-bin-sign',
    '🚰': 'potable-water',
    '♿': 'wheelchair',
    '🚹': 'mens-room',
    '🚺': 'womens-room',
    '🚻': 'restroom',
    '🚼': 'baby-symbol',
    '🚾': 'water-closet',
    '🛂': 'passport-control',
    '🛃': 'customs',
    '🛄': 'baggage-claim',
    '🛅': 'left-luggage',
    '🛗': 'elevator',
    '🆎': 'ab-button-blood-type',
    '🆑': 'cl-button',
    '🆒': 'cool-button',
    '🆓': 'free-button',
    'ℹ️': 'information',
    '🆔': 'id-button',
    'Ⓜ️': 'circled-m',
    '🆕': 'new-button',
    '🆖': 'ng-button',
    '🅾️': 'o-button-blood-type',
    '🆗': 'ok-button',
    '🅿️': 'parking-button',
    '🆘': 'sos-button',
    '🆙': 'up-button',
    '🆚': 'vs-button',
    '🈁': 'japanese-here-button',
    '🈂️': 'japanese-service-charge-button',
    '🈷️': 'japanese-monthly-amount-button',
    '🈶': 'japanese-not-free-of-charge-button',
    '🈯': 'japanese-reserved-button',
    '🉐': 'japanese-bargain-button',
    '🈹': 'japanese-discount-button',
    '🈚': 'japanese-free-of-charge-button',
    '🈲': 'japanese-prohibited-button',
    '🉑': 'japanese-acceptable-button',
    '🈸': 'japanese-application-button',
    '🈴': 'japanese-passing-grade-button',
    '🈳': 'japanese-vacancy-button',
    '㊗️': 'japanese-congratulations-button',
    '㊙️': 'japanese-secret-button',
    '🈺': 'japanese-open-for-business-button',
    '🈵': 'japanese-no-vacancy-button',
  },

  // CDN base URL
  cdn: 'https://cdn.jsdelivr.net/gh/nicehash/FluentEmoji/assets/',

  // Convert emoji to <img> tag
  img(emoji, size = 20) {
    const name = this.map[emoji];
    if (!name) return emoji; // fallback to text emoji
    return `<img class="fe" src="${this.cdn}${name}.svg" alt="${emoji}" width="${size}" height="${size}" style="display:inline-block;vertical-align:middle;" onerror="this.replaceWith('${emoji}')" />`;
  },

  // Convert all emojis in a string
  convert(str, size = 20) {
    if (!str) return str;
    // Match emoji characters (including multi-codepoint sequences)
    return str.replace(/[\u{1F300}-\u{1F9FF}\u{2600}-\u{26FF}\u{2700}-\u{27BF}\u{FE00}-\u{FE0F}\u{1F000}-\u{1FFFF}]/gu, (match) => {
      return this.img(match, size);
    });
  }
};

// Shorthand
function fe(emoji, size) { return FE.img(emoji, size || 20); }

window.FE = FE;
window.fe = fe;
